# API URLs
localai_url: "http://localhost:8080/v1/chat/completions"
openai_api_url: "https://api.openai.com/v1/chat/completions"
anthropic_api_url: "https://api.anthropic.com/v1/messages"

# Default model
default_model: "meta-llama-3.1-8b-instruct"
claude_model: "claude-3-5-sonnet-20240620"

# File paths
system_instruction_dir: "prompts/system_instruction"
scenarios_dir: "prompts"
system_prompt_file: "llm_judge_4_aspects.txt"

# Model parameters
temperature: 0.9
top_p: 0.95
max_tokens: 1024